include $(THEOS)/makefiles/common.mk

BUNDLE_NAME = CustomSnoozePrefs

CustomSnoozePrefs_FILES = CSZRootListController.m
CustomSnoozePrefs_FRAMEWORKS = UIKit
CustomSnoozePrefs_PRIVATE_FRAMEWORKS = Preferences
CustomSnoozePrefs_INSTALL_PATH = /Library/PreferenceBundles
CustomSnoozePrefs_CFLAGS = -fobjc-arc

include $(THEOS_MAKE_PATH)/bundle.mk
